/** Generated by scripts/vendor-echarts-catalog.mjs from Apache ECharts. See /echarts-official/LICENSE. */
export type EChartsOfficialExample = {
  id: string;
  title: string;
  titleCN: string;
  category: string[];
  isGL: boolean;
  ts?: boolean;
  since?: string;
  theme?: string;
};

export type EChartsOfficialCategory = { id: string; label: string; icon: string };

export const ECHARTS_UPSTREAM = {
  "commit": "88ca004030e999073a15303e5fe32462b8fefae2",
  "repository": "https://github.com/apache/echarts-examples",
  "gallery": "https://echarts.apache.org/examples/zh/index.html",
  "version": "6.1.0"
} as const;

export const ECHARTS_CATEGORIES: EChartsOfficialCategory[] = [
  {
    "id": "line",
    "label": "折线图",
    "icon": "/echarts-official/icons/line.svg"
  },
  {
    "id": "bar",
    "label": "柱状图",
    "icon": "/echarts-official/icons/bar.svg"
  },
  {
    "id": "pie",
    "label": "饼图",
    "icon": "/echarts-official/icons/pie.svg"
  },
  {
    "id": "scatter",
    "label": "散点图",
    "icon": "/echarts-official/icons/scatter.svg"
  },
  {
    "id": "map",
    "label": "地理坐标/地图",
    "icon": "/echarts-official/icons/map.svg"
  },
  {
    "id": "candlestick",
    "label": "K 线图",
    "icon": "/echarts-official/icons/candlestick.svg"
  },
  {
    "id": "radar",
    "label": "雷达图",
    "icon": "/echarts-official/icons/radar.svg"
  },
  {
    "id": "boxplot",
    "label": "盒须图",
    "icon": "/echarts-official/icons/boxplot.svg"
  },
  {
    "id": "heatmap",
    "label": "热力图",
    "icon": "/echarts-official/icons/heatmap.svg"
  },
  {
    "id": "graph",
    "label": "关系图",
    "icon": "/echarts-official/icons/graph.svg"
  },
  {
    "id": "lines",
    "label": "路径图",
    "icon": "/echarts-official/icons/lines.svg"
  },
  {
    "id": "tree",
    "label": "树图",
    "icon": "/echarts-official/icons/tree.svg"
  },
  {
    "id": "treemap",
    "label": "矩形树图",
    "icon": "/echarts-official/icons/treemap.svg"
  },
  {
    "id": "sunburst",
    "label": "旭日图",
    "icon": "/echarts-official/icons/sunburst.svg"
  },
  {
    "id": "parallel",
    "label": "平行坐标系",
    "icon": "/echarts-official/icons/parallel.svg"
  },
  {
    "id": "sankey",
    "label": "桑基图",
    "icon": "/echarts-official/icons/sankey.svg"
  },
  {
    "id": "funnel",
    "label": "漏斗图",
    "icon": "/echarts-official/icons/funnel.svg"
  },
  {
    "id": "gauge",
    "label": "仪表盘",
    "icon": "/echarts-official/icons/gauge.svg"
  },
  {
    "id": "pictorialBar",
    "label": "象形柱图",
    "icon": "/echarts-official/icons/pictorialBar.svg"
  },
  {
    "id": "themeRiver",
    "label": "主题河流图",
    "icon": "/echarts-official/icons/themeRiver.svg"
  },
  {
    "id": "calendar",
    "label": "日历坐标系",
    "icon": "/echarts-official/icons/calendar.svg"
  },
  {
    "id": "matrix",
    "label": "矩阵坐标系",
    "icon": "/echarts-official/icons/matrix.svg"
  },
  {
    "id": "chord",
    "label": "和弦图",
    "icon": "/echarts-official/icons/chord.svg"
  },
  {
    "id": "custom",
    "label": "自定义系列",
    "icon": "/echarts-official/icons/custom.svg"
  },
  {
    "id": "dataset",
    "label": "数据集",
    "icon": "/echarts-official/icons/dataset.svg"
  },
  {
    "id": "dataZoom",
    "label": "数据区域缩放",
    "icon": "/echarts-official/icons/dataZoom.svg"
  },
  {
    "id": "graphic",
    "label": "图形组件",
    "icon": "/echarts-official/icons/graphic.svg"
  },
  {
    "id": "rich",
    "label": "富文本",
    "icon": "/echarts-official/icons/rich.svg"
  },
  {
    "id": "globe",
    "label": "3D 地球",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "bar3D",
    "label": "3D 柱状图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "scatter3D",
    "label": "3D 散点图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "surface",
    "label": "3D 曲面",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "map3D",
    "label": "3D 地图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "lines3D",
    "label": "3D 路径图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "line3D",
    "label": "3D 折线图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "scatterGL",
    "label": "GL 散点图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "linesGL",
    "label": "GL 路径图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "flowGL",
    "label": "GL 矢量场图",
    "icon": "/echarts-official/icons/gl.svg"
  },
  {
    "id": "graphGL",
    "label": "GL 关系图",
    "icon": "/echarts-official/icons/gl.svg"
  }
];

export const ECHARTS_EXAMPLES: EChartsOfficialExample[] = [
  {
    "id": "bar-histogram",
    "title": "Histogram with Custom Series",
    "titleCN": "直方图（自定义系列）",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-simple",
    "title": "Basic Bar",
    "titleCN": "基础柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-tick-align",
    "title": "Axis Align with Tick",
    "titleCN": "坐标轴刻度与标签对齐",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-simple",
    "title": "Simple Calendar",
    "titleCN": "基础日历图",
    "category": [
      "calendar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "candlestick-simple",
    "title": "Basic Candlestick",
    "titleCN": "基础 K 线图",
    "category": [
      "candlestick"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "chord-simple",
    "title": "Basic Chord",
    "titleCN": "基础和弦图",
    "category": [
      "chord"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "data-transform-sort-bar",
    "title": "Sort Data in Bar Chart",
    "titleCN": "柱状图排序",
    "category": [
      "dataset",
      "bar",
      "transform"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "heatmap-cartesian",
    "title": "Heatmap on Cartesian",
    "titleCN": "笛卡尔坐标系上的热力图",
    "category": [
      "heatmap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-simple",
    "title": "Basic Line Chart",
    "titleCN": "基础折线图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-smooth",
    "title": "Smoothed Line Chart",
    "titleCN": "基础平滑折线图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-simple",
    "title": "Referer of a Website",
    "titleCN": "某站点用户访问来源",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "radar",
    "title": "Basic Radar Chart",
    "titleCN": "基础雷达图",
    "category": [
      "radar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sankey-simple",
    "title": "Basic Sankey",
    "titleCN": "基础桑基图",
    "category": [
      "sankey"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-simple",
    "title": "Basic Scatter Chart",
    "titleCN": "基础散点图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "area-basic",
    "title": "Basic area chart",
    "titleCN": "基础面积图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-background",
    "title": "Bar with Background",
    "titleCN": "带背景色的柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-data-color",
    "title": "Set Style of Single Bar.",
    "titleCN": "自定义单个柱子颜色",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-waterfall",
    "title": "Waterfall Chart",
    "titleCN": "瀑布图（柱状图模拟）",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-heatmap",
    "title": "Calendar Heatmap",
    "titleCN": "日历热力图",
    "category": [
      "calendar",
      "heatmap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-vertical",
    "title": "Calendar Heatmap Vertical",
    "titleCN": "纵向日历图",
    "category": [
      "calendar",
      "heatmap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "chord-minAngle",
    "title": "Chord minAngle",
    "titleCN": "和弦图 minAngle",
    "category": [
      "chord"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "custom-ohlc",
    "title": "OHLC Chart",
    "titleCN": "OHLC 图（使用自定义系列）",
    "category": [
      "candlestick"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-profit",
    "title": "Profit",
    "titleCN": "利润分布直方图",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dataset-encode0",
    "title": "Simple Encode",
    "titleCN": "指定数据到坐标轴的映射",
    "category": [
      "dataset",
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge",
    "title": "Gauge Basic chart",
    "titleCN": "基础仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-simple",
    "title": "Simple Gauge",
    "titleCN": "带标签数字动画的基础仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-force2",
    "title": "Force Layout",
    "titleCN": "力引导布局",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-stack",
    "title": "Stacked Line Chart",
    "titleCN": "堆叠折线图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "matrix-simple",
    "title": "Simple Matrix",
    "titleCN": "简单的矩阵图",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "parallel-simple",
    "title": "Basic Parallel",
    "titleCN": "基础平行坐标",
    "category": [
      "parallel"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-borderRadius",
    "title": "Doughnut Chart with Rounded Corner",
    "titleCN": "圆角环形图",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-doughnut",
    "title": "Doughnut Chart",
    "titleCN": "环形图",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-half-donut",
    "title": "Half Doughnut Chart",
    "titleCN": "半环形图",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-padAngle",
    "title": "Pie with padAngle",
    "titleCN": "饼图扇区间隙",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "radar-aqi",
    "title": "AQI - Radar Chart",
    "titleCN": "AQI - 雷达图",
    "category": [
      "radar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sankey-vertical",
    "title": "Sankey Orient Vertical",
    "titleCN": "垂直方向的桑基图",
    "category": [
      "sankey"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-anscombe-quartet",
    "title": "Anscomb's quartet",
    "titleCN": "安斯库姆四重奏",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-clustering",
    "title": "Clustering Process",
    "titleCN": "数据聚合",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-clustering-process",
    "title": "Clustering Process",
    "titleCN": "聚合过程可视化",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "scatter-exponential-regression",
    "title": "Exponential Regression",
    "titleCN": "指数回归（使用统计插件）",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sunburst-simple",
    "title": "Basic Sunburst",
    "titleCN": "基础旭日图",
    "category": [
      "sunburst"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "area-stack",
    "title": "Stacked Area Chart",
    "titleCN": "堆叠面积图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "area-stack-gradient",
    "title": "Gradient Stacked Area Chart",
    "titleCN": "渐变堆叠面积图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-negative2",
    "title": "Bar Chart with Negative Value",
    "titleCN": "交错正负轴标签",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-polar-label-radial",
    "title": "Radial Polar Bar Label Position",
    "titleCN": "极坐标柱状图标签",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-polar-label-tangential",
    "title": "Tangential Polar Bar Label Position",
    "titleCN": "极坐标柱状图标签",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-y-category",
    "title": "World Population",
    "titleCN": "世界人口总量 - 条形图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bump-chart",
    "title": "Bump Chart (Ranking)",
    "titleCN": "凹凸图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-horizontal",
    "title": "Calendar Heatmap Horizontal",
    "titleCN": "横向日历图",
    "category": [
      "calendar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "candlestick-sh",
    "title": "ShangHai Index",
    "titleCN": "上证指数",
    "category": [
      "candlestick"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-error-scatter",
    "title": "Error Scatter on Catesian",
    "titleCN": "使用自定系列给散点图添加误差范围",
    "category": [
      "custom",
      "dataZoom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-speed",
    "title": "Speed Gauge",
    "titleCN": "速度仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-grid",
    "title": "Graph on Cartesian",
    "titleCN": "笛卡尔坐标系上的 Graph",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-simple",
    "title": "Simple Graph",
    "titleCN": "Graph 简单示例",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "heatmap-large",
    "title": "Heatmap - 20K data",
    "titleCN": "热力图 - 2w 数据",
    "category": [
      "heatmap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "heatmap-large-piecewise",
    "title": "Heatmap - Discrete Mapping of Color",
    "titleCN": "热力图 - 颜色的离散映射",
    "category": [
      "heatmap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-marker",
    "title": "Temperature Change in the Coming Week",
    "titleCN": "未来一周气温变化",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "matrix-correlation-heatmap",
    "title": "Correlation Matrix (Heatmap)",
    "titleCN": "相关矩阵（热力图）",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "matrix-correlation-scatter",
    "title": "Correlation Matrix (Scatter)",
    "titleCN": "相关矩阵（散点图）",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "matrix-covariance",
    "title": "Covariance Matrix",
    "titleCN": "协方差矩阵",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "matrix-graph",
    "title": "Graph Chart in Matrix",
    "titleCN": "矩阵布局下的关系图",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "matrix-pie",
    "title": "Pie Charts in Matrix",
    "titleCN": "矩阵布局下的饼图",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "parallel-aqi",
    "title": "Parallel Aqi",
    "titleCN": "AQI 分布（平行坐标）",
    "category": [
      "parallel"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-custom",
    "title": "Customized Pie",
    "titleCN": "饼图自定义样式",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-pattern",
    "title": "Texture on Pie Chart",
    "titleCN": "饼图纹理",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-roseType",
    "title": "Nightingale Chart",
    "titleCN": "南丁格尔玫瑰图",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-roseType-simple",
    "title": "Nightingale Chart",
    "titleCN": "基础南丁格尔玫瑰图",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "polar-endAngle",
    "title": "Polar endAngle",
    "titleCN": "极坐标系 endAngle",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "radar-custom",
    "title": "Customized Radar Chart",
    "titleCN": "自定义雷达图",
    "category": [
      "radar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sankey-itemstyle",
    "title": "Specify ItemStyle for Each Node in Sankey",
    "titleCN": "桑基图节点自定义样式",
    "category": [
      "sankey"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sankey-levels",
    "title": "Sankey with Levels Setting",
    "titleCN": "桑基图层级自定义样式",
    "category": [
      "sankey"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-effect",
    "title": "Effect Scatter Chart",
    "titleCN": "涟漪特效散点图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-linear-regression",
    "title": "Linear Regression",
    "titleCN": "线性回归（使用统计插件）",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-polynomial-regression",
    "title": "Polynomial Regression",
    "titleCN": "多项式回归（使用统计插件）",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sunburst-borderRadius",
    "title": "Sunburst with Rounded Corner",
    "titleCN": "圆角旭日图",
    "category": [
      "sunburst"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sunburst-label-rotate",
    "title": "Sunburst Label Rotate",
    "titleCN": "旭日图标签旋转",
    "category": [
      "sunburst"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "area-pieces",
    "title": "Area Pieces",
    "titleCN": "折线图区域高亮",
    "category": [
      "line",
      "visualMap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-breaks-simple",
    "title": "Bar Chart with Axis Breaks",
    "titleCN": "断轴上的柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "bar-gradient",
    "title": "Clickable Column Chart with Gradient",
    "titleCN": "特性示例：渐变色 阴影 点击缩放",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-label-rotation",
    "title": "Bar Label Rotation",
    "titleCN": "柱状图标签旋转",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-stack",
    "title": "Stacked Column Chart",
    "titleCN": "堆叠柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-stack-borderRadius",
    "title": "Stacked Bar with borderRadius",
    "titleCN": "带圆角的堆积柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-stack-normalization",
    "title": "Stacked Bar Normalization",
    "titleCN": "堆叠柱状图的归一化",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-stack-normalization-and-variation",
    "title": "Stacked Bar Normalization and Variation",
    "titleCN": "堆叠柱状图的归一化和变化",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-waterfall2",
    "title": "Waterfall Chart",
    "titleCN": "阶梯瀑布图（柱状图模拟）",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-y-category-stack",
    "title": "Stacked Horizontal Bar",
    "titleCN": "堆叠条形图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "candlestick-large",
    "title": "Large Scale Candlestick",
    "titleCN": "大数据量K线图",
    "category": [
      "candlestick"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "chord-lineStyle-color",
    "title": "Chord lineStyle.color",
    "titleCN": "和弦图边的颜色",
    "category": [
      "chord"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "custom-bar-trend",
    "title": "Custom Bar Trend",
    "titleCN": "使用自定义系列添加柱状图趋势",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-cartesian-polygon",
    "title": "Custom Cartesian Polygon",
    "titleCN": "自定义多边形图",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-error-bar",
    "title": "Error Bar on Catesian",
    "titleCN": "使用自定系列给柱状图添加误差范围",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-profile",
    "title": "Profile",
    "titleCN": "性能分析图",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "cycle-plot",
    "title": "Cycle Plot",
    "titleCN": "周期图",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "data-transform-filter",
    "title": "Data Transform Filter",
    "titleCN": "数据过滤",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "data-transform-multiple-pie",
    "title": "Partition Data to Pies",
    "titleCN": "分割数据到数个饼图",
    "category": [
      "dataset",
      "pie",
      "transform"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dataset-default",
    "title": "Default arrangement",
    "titleCN": "默认 encode 设置",
    "category": [
      "dataset",
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dataset-encode1",
    "title": "Encode and Matrix",
    "titleCN": "指定数据到坐标轴的映射",
    "category": [
      "dataset"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-progress",
    "title": "Progress Gauge",
    "titleCN": "进度仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-stage",
    "title": "Stage Speed Gauge",
    "titleCN": "阶段速度仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-graph",
    "title": "Geo Graph",
    "titleCN": "地理坐标系上的关系图",
    "category": [
      "map",
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-force",
    "title": "Force Layout",
    "titleCN": "力引导布局",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-label-overlap",
    "title": "Hide Overlapped Label",
    "titleCN": "关系图自动隐藏重叠标签",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-gradient",
    "title": "Line Gradient",
    "titleCN": "折线图的渐变",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-sections",
    "title": "Distribution of Electricity",
    "titleCN": "一天用电量分布",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "matrix-confusion",
    "title": "Confusion Matrix",
    "titleCN": "混淆矩阵",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "matrix-grid-layout",
    "title": "Responsive grid layout based on matrix",
    "titleCN": "矩阵中响应式网格布局",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": false,
    "since": "6.0.0"
  },
  {
    "id": "matrix-stock",
    "title": "Matrix Stock Application",
    "titleCN": "股市矩阵图",
    "category": [
      "matrix",
      "candlestick"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "pie-alignTo",
    "title": "Pie Label Align",
    "titleCN": "饼图标签对齐",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-labelLine-adjust",
    "title": "Label Line Adjust",
    "titleCN": "饼图引导线调整",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "radar2",
    "title": "Proportion of Browsers",
    "titleCN": "浏览器占比变化",
    "category": [
      "radar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sankey-energy",
    "title": "Gradient Edge",
    "titleCN": "桑基图渐变色边",
    "category": [
      "sankey"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sankey-nodeAlign-left",
    "title": "Node Align Left in Sankey",
    "titleCN": "桑基图左对齐布局",
    "category": [
      "sankey"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sankey-nodeAlign-right",
    "title": "Node Align Right in Sankey",
    "titleCN": "桑基图右对齐布局",
    "category": [
      "sankey"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-jitter",
    "title": "Scatter with Jittering",
    "titleCN": "带抖动的散点图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "scatter-punchCard",
    "title": "Punch Card of Github",
    "titleCN": "GitHub 打卡气泡图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-single-axis",
    "title": "Scatter on Single Axis",
    "titleCN": "单轴散点图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-weight",
    "title": "Distribution of Height and Weight",
    "titleCN": "男性女性身高体重分布",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sunburst-monochrome",
    "title": "Monochrome Sunburst",
    "titleCN": "单色旭日图",
    "category": [
      "sunburst"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "area-simple",
    "title": "Large scale area chart",
    "titleCN": "大数据量面积图",
    "category": [
      "line",
      "dataZoom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-brush",
    "title": "Brush Select on Column Chart",
    "titleCN": "柱状图框选",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-negative",
    "title": "Bar Chart with Negative Value",
    "titleCN": "正负条形图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar1",
    "title": "Rainfall and Evaporation",
    "titleCN": "某地区蒸发量和降水量",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-graph",
    "title": "Calendar Graph",
    "titleCN": "日历关系图",
    "category": [
      "calendar",
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-lunar",
    "title": "Calendar Lunar",
    "titleCN": "农历日历图",
    "category": [
      "calendar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "candlestick-touch",
    "title": "Axis Pointer Link and Touch",
    "titleCN": "触屏上的坐标轴指示器",
    "category": [
      "candlestick"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "confidence-band",
    "title": "Confidence Band",
    "titleCN": "置信带",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-gantt-flight",
    "title": "Gantt Chart of Airport Flights",
    "titleCN": "机场航班甘特图",
    "category": [
      "custom",
      "dataZoom"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "custom-polar-heatmap",
    "title": "Polar Heatmap",
    "titleCN": "极坐标热力图（自定义系列）",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "data-transform-aggregate",
    "title": "Data Transform Simple Aggregate",
    "titleCN": "简单的数据聚合",
    "category": [
      "boxplot"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "flame-graph",
    "title": "Flame graph",
    "titleCN": "火焰图",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-grade",
    "title": "Grade Gauge",
    "titleCN": "等级仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-multi-title",
    "title": "Multi Title Gauge",
    "titleCN": "多标题仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-temperature",
    "title": "Temperature Gauge chart",
    "titleCN": "气温仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph",
    "title": "Les Miserables",
    "titleCN": "悲惨世界人物关系图",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "grid-multiple",
    "title": "Rainfall vs Evaporation",
    "titleCN": "雨量蒸发量关系图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "intraday-breaks-1",
    "title": "Intraday Chart with Breaks",
    "titleCN": "断轴上的日内走势图",
    "category": [
      "candlestick",
      "line"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "intraday-breaks-2",
    "title": "Intraday Chart with Breaks (II)",
    "titleCN": "断轴上的日内走势图 (II)",
    "category": [
      "candlestick",
      "line"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "line-aqi",
    "title": "Beijing AQI",
    "titleCN": "北京 AQI 可视化",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "mix-line-bar",
    "title": "Mixed Line and Bar",
    "titleCN": "折柱混合",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "mix-zoom-on-value",
    "title": "Mix Zoom On Value",
    "titleCN": "多数值轴轴缩放",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "multiple-x-axis",
    "title": "Multiple X Axes",
    "titleCN": "多 X 轴",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "multiple-y-axis",
    "title": "Multiple Y Axes",
    "titleCN": "多 Y 轴示例",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "parallel-nutrients",
    "title": "Parallel Nutrients",
    "titleCN": "营养结构（平行坐标）",
    "category": [
      "parallel"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pictorialBar-bar-transition",
    "title": "Transition between pictorialBar and bar",
    "titleCN": "象形主图变形为柱状图",
    "category": [
      "pictorialBar",
      "animation"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-legend",
    "title": "Pie with Scrollable Legend",
    "titleCN": "可滚动的图例",
    "category": [
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-rich-text",
    "title": "Pie Special Label",
    "titleCN": "富文本标签",
    "category": [
      "pie",
      "rich"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-aggregate-bar",
    "title": "Aggregate Scatter to Bar",
    "titleCN": "散点图聚合为柱状图动画",
    "category": [
      "scatter",
      "animation"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-label-align-right",
    "title": "Align Label on the Top",
    "titleCN": "散点图标签顶部对齐",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-label-align-top",
    "title": "Align Label on the Top",
    "titleCN": "散点图标签顶部对齐",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-symbol-morph",
    "title": "Symbol Shape Morph",
    "titleCN": "散点图变形动画",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sunburst-visualMap",
    "title": "Sunburst VisualMap",
    "titleCN": "旭日图使用视觉编码",
    "category": [
      "sunburst"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "treemap-sunburst-transition",
    "title": "Transition between Treemap and Sunburst",
    "titleCN": "矩形树图和旭日图的动画过渡",
    "category": [
      "treemap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "area-rainfall",
    "title": "Rainfall",
    "titleCN": "雨量流量关系图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "area-time-axis",
    "title": "Area Chart with Time Axis",
    "titleCN": "时间轴折线图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-animation-delay",
    "title": "Animation Delay",
    "titleCN": "柱状图动画延迟",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-drilldown",
    "title": "Bar Chart Drilldown Animation",
    "titleCN": "柱状图下钻动画",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-large",
    "title": "Large Scale Bar Chart",
    "titleCN": "大数据量柱图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-race",
    "title": "Bar Race",
    "titleCN": "动态排序柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dataset-link",
    "title": "Share Dataset",
    "titleCN": "联动和共享数据集",
    "category": [
      "dataset",
      "line",
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dataset-series-layout-by",
    "title": "Series Layout By Column or Row",
    "titleCN": "系列按行和按列排布",
    "category": [
      "dataset",
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dataset-simple0",
    "title": "Simple Example of Dataset",
    "titleCN": "最简单的数据集（dataset）",
    "category": [
      "dataset",
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dataset-simple1",
    "title": "Dataset in Object Array",
    "titleCN": "对象数组的输入格式",
    "category": [
      "dataset",
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "dynamic-data2",
    "title": "Dynamic Data + Time Axis",
    "titleCN": "动态数据 + 时间坐标轴",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-ring",
    "title": "Ring Gauge",
    "titleCN": "得分环",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-choropleth-scatter",
    "title": "Geo Choropleth and Scatter",
    "titleCN": "地理坐标系上的等值区划图和散点图",
    "category": [
      "map",
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-circular-layout",
    "title": "Les Miserables",
    "titleCN": "悲惨世界人物关系图(环形布局)",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graphic-stroke-animation",
    "title": "Stroke Animation",
    "titleCN": "关键帧描边动画",
    "category": [
      "graphic"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-function",
    "title": "Function Plot",
    "titleCN": "函数绘图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-race",
    "title": "Line Race",
    "titleCN": "动态排序折线图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "map-iceland-pie",
    "title": "Pie Charts on GEO Map",
    "titleCN": "在地图上显示饼图",
    "category": [
      "map",
      "pie"
    ],
    "isGL": false,
    "ts": true,
    "since": "5.4.0"
  },
  {
    "id": "matrix-sparkline",
    "title": "Mini Line Charts (Sparkline) in Matrix",
    "titleCN": "矩阵中的微型折线图",
    "category": [
      "matrix",
      "line"
    ],
    "isGL": false,
    "ts": false,
    "since": "6.0.0"
  },
  {
    "id": "pie-nest",
    "title": "Nested Pies",
    "titleCN": "嵌套环形图",
    "category": [
      "pie",
      "rich"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-large",
    "title": "Large Scatter",
    "titleCN": "大规模散点图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-nebula",
    "title": "Scatter Nebula",
    "titleCN": "大规模星云散点图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-stream-visual",
    "title": "Visual interaction with stream",
    "titleCN": "流式渲染和视觉映射操作",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "sunburst-drink",
    "title": "Drink Flavors",
    "titleCN": "饮品风味分类",
    "category": [
      "sunburst"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "wind-barb",
    "title": "Wind Barb",
    "titleCN": "风向图",
    "category": [
      "custom",
      "dataZoom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-multi-drilldown",
    "title": "Bar Chart Multi-level Drilldown Animation",
    "titleCN": "柱状图多层下钻动画",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-race-country",
    "title": "Bar Race",
    "titleCN": "动态排序柱状图 - 人均收入",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-rich-text",
    "title": "Weather Statistics",
    "titleCN": "天气统计（富文本）",
    "category": [
      "bar",
      "rich"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bubble-gradient",
    "title": "Bubble Chart",
    "titleCN": "气泡图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-pie",
    "title": "Calendar Pie",
    "titleCN": "日历饼图",
    "category": [
      "calendar",
      "pie"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-hexbin",
    "title": "Hexagonal Binning",
    "titleCN": "六边形分箱图（自定义系列）",
    "category": [
      "custom",
      "map"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "dynamic-data",
    "title": "Dynamic Data",
    "titleCN": "动态数据",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-barometer",
    "title": "Gauge Barometer chart",
    "titleCN": "气压表",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-force-dynamic",
    "title": "Graph Dynamic",
    "titleCN": "动态增加图节点",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graphic-loading",
    "title": "Customized Loading Animation",
    "titleCN": "加载动画",
    "category": [
      "graphic"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-markline",
    "title": "Line with Marklines",
    "titleCN": "折线图的标记线",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-style",
    "title": "Line Style and Item Style",
    "titleCN": "自定义折线图样式",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "matrix-mini-bar-geo",
    "title": "Mini Bars and Geo in Matrix",
    "titleCN": "矩阵坐标系下的微型条形图和地图",
    "category": [
      "matrix",
      "bar",
      "geo"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "mix-timeline-finance",
    "title": "Finance Indices 2002",
    "titleCN": "2002全国宏观经济指标",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "sunburst-book",
    "title": "Book Records",
    "titleCN": "书籍分布",
    "category": [
      "sunburst"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "watermark",
    "title": "Watermark - ECharts Download",
    "titleCN": "水印 - ECharts 下载统计",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-polar-real-estate",
    "title": "Bar Chart on Polar",
    "titleCN": "极坐标系下的柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-polar-stack",
    "title": "Stacked Bar Chart on Polar",
    "titleCN": "极坐标系下的堆叠柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-polar-stack-radial",
    "title": "Stacked Bar Chart on Polar(Radial)",
    "titleCN": "极坐标系下的堆叠柱状图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-calendar-icon",
    "title": "Custom Calendar Icon",
    "titleCN": "日历图自定义图标",
    "category": [
      "custom",
      "calendar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-wind",
    "title": "Use custom series to draw wind vectors",
    "titleCN": "使用自定义系列绘制风场",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "gauge-clock",
    "title": "Clock",
    "titleCN": "时钟仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-life-expectancy",
    "title": "Graph Life Expectancy",
    "titleCN": "预期寿命",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-in-cartesian-coordinate-system",
    "title": "Line Chart in Cartesian Coordinate System",
    "titleCN": "双数值轴折线图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-log",
    "title": "Log Axis",
    "titleCN": "对数轴示例",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-step",
    "title": "Step Line",
    "titleCN": "阶梯折线图",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "polar-roundCap",
    "title": "Rounded Bar on Polar",
    "titleCN": "圆角环形图",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-aqi-color",
    "title": "Scatter Aqi Color",
    "titleCN": "AQI 气泡图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-nutrients",
    "title": "Scatter Nutrients",
    "titleCN": "营养分布散点图",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-nutrients-matrix",
    "title": "Scatter Nutrients Matrix",
    "titleCN": "营养分布散点矩阵",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "bar-breaks-brush",
    "title": "Bar Chart with Axis Breaks (Brush-enabled)",
    "titleCN": "断轴上的柱状图（可刷选）",
    "category": [
      "bar"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "gauge-car",
    "title": "Gauge Car",
    "titleCN": "汽车仪表盘",
    "category": [
      "gauge"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graph-webkit-dep",
    "title": "Graph Webkit Dep",
    "titleCN": "WebKit 模块关系依赖图",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-easing",
    "title": "Line Easing Visualizing",
    "titleCN": "缓动函数可视化",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-fisheye-lens",
    "title": "Fisheye Lens on Line Chart",
    "titleCN": "折线图鱼眼放大",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "line-y-category",
    "title": "Line Y Category",
    "titleCN": "垂直折线图（Y轴为类目轴）",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-polar-punchCard",
    "title": "Punch Card of Github",
    "titleCN": "GitHub 打卡气泡图（极坐标）",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "custom-gauge",
    "title": "Custom Gauge",
    "titleCN": "自定义仪表",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "graph-npm",
    "title": "NPM Dependencies",
    "titleCN": "NPM 依赖关系图",
    "category": [
      "graph"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-graphic",
    "title": "Custom Graphic Component",
    "titleCN": "自定义图形组件",
    "category": [
      "line",
      "graphic"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-pen",
    "title": "Click to Add Points",
    "titleCN": "点击添加折线图拐点",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-life-expectancy-timeline",
    "title": "Life Expectancy and GDP",
    "titleCN": "各国人均寿命与GDP关系演变",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "scatter-painter-choice",
    "title": "Master Painter Color Choices Throughout History",
    "titleCN": "历代绘画大师的色彩运用",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "boxplot-light-velocity",
    "title": "Boxplot Light Velocity",
    "titleCN": "基础盒须图",
    "category": [
      "boxplot"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "boxplot-light-velocity2",
    "title": "Boxplot Light Velocity2",
    "titleCN": "垂直方向盒须图",
    "category": [
      "boxplot"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "boxplot-multi",
    "title": "Multiple Categories",
    "titleCN": "多系列盒须图",
    "category": [
      "boxplot"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "candlestick-brush",
    "title": "Candlestick Brush",
    "titleCN": "K 线图刷选",
    "category": [
      "candlestick"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "candlestick-sh-2015",
    "title": "ShangHai Index, 2015",
    "titleCN": "2015 年上证指数",
    "category": [
      "candlestick"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "chord-style",
    "title": "Chord Style",
    "titleCN": "和弦图样式",
    "category": [
      "chord"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "funnel",
    "title": "Funnel Chart",
    "titleCN": "漏斗图",
    "category": [
      "funnel"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "funnel-align",
    "title": "Funnel Compare",
    "titleCN": "漏斗图(对比)",
    "category": [
      "funnel"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "funnel-customize",
    "title": "Customized Funnel",
    "titleCN": "漏斗图",
    "category": [
      "funnel"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "funnel-mutiple",
    "title": "Multiple Funnels",
    "titleCN": "多漏斗图",
    "category": [
      "funnel"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-beef-cuts",
    "title": "GEO Beef Cuts",
    "titleCN": "庖丁解牛",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-organ",
    "title": "Organ Data with SVG",
    "titleCN": "内脏数据（SVG）",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "geo-seatmap-flight",
    "title": "Flight Seatmap with SVG",
    "titleCN": "航班选座（SVG）",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-svg-custom-effect",
    "title": "GEO SVG with Customized Effect",
    "titleCN": "自定义特效",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-svg-lines",
    "title": "GEO SVG Lines",
    "titleCN": "GEO 路径图（SVG）",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-svg-map",
    "title": "GEO SVG Map",
    "titleCN": "地图（SVG）",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-svg-scatter-simple",
    "title": "GEO SVG Scatter",
    "titleCN": "散点图（SVG）",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "geo-svg-traffic",
    "title": "GEO SVG Traffic",
    "titleCN": "交通（SVG）",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "graphic-wave-animation",
    "title": "Wave Animation",
    "titleCN": "波浪动画",
    "category": [
      "graphic"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "line-polar",
    "title": "Two Value-Axes in Polar",
    "titleCN": "极坐标双数值轴",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-polar2",
    "title": "Two Value-Axes in Polar",
    "titleCN": "极坐标双数值轴",
    "category": [
      "line"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "line-tooltip-touch",
    "title": "Tooltip and DataZoom on Mobile",
    "titleCN": "移动端上的 dataZoom 和 tooltip",
    "category": [
      "line",
      "dataZoom"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "lines-ny",
    "title": "Use lines to draw 1 million New York streets",
    "titleCN": "使用线图绘制近100万纽约街道数据",
    "category": [
      "map",
      "lines"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "map-bar-morph",
    "title": "Morphing between Map and Bar",
    "titleCN": "地图柱状图变形动画",
    "category": [
      "map",
      "animation"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "map-HK",
    "title": "Population Density of HongKong (2011)",
    "titleCN": "香港18区人口密度 （2011）",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "map-usa",
    "title": "USA Population Estimates (2012)",
    "titleCN": "2012 年美国人口统计",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "map-usa-projection",
    "title": "USA Choropleth Map with Projection",
    "titleCN": "自定义地图投影",
    "category": [
      "map"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "matrix-periodic-table",
    "title": "Periodic Table",
    "titleCN": "元素周期表",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "pictorialBar-body-fill",
    "title": "Water Content",
    "titleCN": "人体含水量",
    "category": [
      "pictorialBar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pictorialBar-dotted",
    "title": "Dotted bar",
    "titleCN": "虚线柱状图效果",
    "category": [
      "pictorialBar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pictorialBar-forest",
    "title": "Expansion of forest",
    "titleCN": "森林的增长",
    "category": [
      "pictorialBar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pictorialBar-hill",
    "title": "Wish List and Mountain Height",
    "titleCN": "圣诞愿望清单和山峰高度",
    "category": [
      "pictorialBar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pictorialBar-spirit",
    "title": "Spirits",
    "titleCN": "精灵",
    "category": [
      "pictorialBar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pictorialBar-vehicle",
    "title": "Vehicles",
    "titleCN": "交通工具",
    "category": [
      "pictorialBar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pictorialBar-velocity",
    "title": "Velocity of Christmas Reindeers",
    "titleCN": "驯鹿的速度",
    "category": [
      "pictorialBar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "pie-parliament-transition",
    "title": "Transition of Parliament and Pie Chart",
    "titleCN": "自定义议会图与饼图过渡动画",
    "category": [
      "custom",
      "animtion"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "radar-multiple",
    "title": "Multiple Radar",
    "titleCN": "多雷达图",
    "category": [
      "radar"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-matrix",
    "title": "Scatter Matrix",
    "titleCN": "散点矩阵和平行坐标",
    "category": [
      "parallel",
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "themeRiver-basic",
    "title": "ThemeRiver",
    "titleCN": "主题河流图",
    "category": [
      "themeRiver"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "themeRiver-lastfm",
    "title": "ThemeRiver Lastfm",
    "titleCN": "Lastfm 主题河流图",
    "category": [
      "themeRiver"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "tree-basic",
    "title": "From Left to Right Tree",
    "titleCN": "从左到右树状图",
    "category": [
      "tree"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "tree-legend",
    "title": "Multiple Trees",
    "titleCN": "多棵树",
    "category": [
      "tree"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "tree-orient-bottom-top",
    "title": "From Bottom to Top Tree",
    "titleCN": "从下到上树状图",
    "category": [
      "tree"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "tree-orient-right-left",
    "title": "From Right to Left Tree",
    "titleCN": "从右到左树状图",
    "category": [
      "tree"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "tree-polyline",
    "title": "Tree with Polyline Edge",
    "titleCN": "折线树图",
    "category": [
      "tree"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "tree-radial",
    "title": "Radial Tree",
    "titleCN": "径向树状图",
    "category": [
      "tree"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "tree-vertical",
    "title": "From Top to Bottom Tree",
    "titleCN": "从上到下树状图",
    "category": [
      "tree"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "treemap-disk",
    "title": "Disk Usage",
    "titleCN": "磁盘占用",
    "category": [
      "treemap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "treemap-drill-down",
    "title": "ECharts Option Query",
    "titleCN": "ECharts 配置项查询分布",
    "category": [
      "treemap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "treemap-obama",
    "title": "How $3.7 Trillion is Spent",
    "titleCN": "3.7 万亿美元支出构成",
    "category": [
      "treemap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "treemap-show-parent",
    "title": "Show Parent Labels",
    "titleCN": "显示父层级标签",
    "category": [
      "treemap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "treemap-simple",
    "title": "Basic Treemap",
    "titleCN": "基础矩形树图",
    "category": [
      "treemap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "treemap-visual",
    "title": "Gradient Mapping",
    "titleCN": "映射为渐变色",
    "category": [
      "treemap"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "calendar-charts",
    "title": "Calendar Charts",
    "titleCN": "日历图",
    "category": [
      "calendar",
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "circle-packing-with-d3",
    "title": "Circle Packing with d3",
    "titleCN": "基于 d3 的圆形包络图",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "custom-spiral-race",
    "title": "Custom Spiral Race",
    "titleCN": "自定义螺旋线竞速",
    "category": [
      "custom"
    ],
    "isGL": false,
    "ts": false
  },
  {
    "id": "matrix-mbti",
    "title": "MBTI Partner Compatibility",
    "titleCN": "MBTI 伴侣相容性",
    "category": [
      "matrix"
    ],
    "isGL": false,
    "ts": true,
    "since": "6.0.0"
  },
  {
    "id": "line-draggable",
    "title": "Draggable Points",
    "titleCN": "可拖拽点",
    "category": [
      "line",
      "graphic"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "scatter-logarithmic-regression",
    "title": "Logarithmic Regression",
    "titleCN": "对数回归（使用统计插件）",
    "category": [
      "scatter"
    ],
    "isGL": false,
    "ts": true
  },
  {
    "id": "globe-echarts-gl-hello-world",
    "title": "ECharts-GL Hello World",
    "titleCN": "ECharts GL 入门",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "globe-atmosphere",
    "title": "Globe with Atmosphere",
    "titleCN": "大气层显示",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "globe-layers",
    "title": "Globe Layers",
    "titleCN": "地球图层",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "animating-contour-on-globe",
    "title": "Animating Contour on Globe",
    "titleCN": "地球等值线动画",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "bar3d-dataset",
    "title": "3D Bar with Dataset",
    "titleCN": "使用 dataset 为三维柱状图设置数据",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "bar3d-global-population",
    "title": "Bar3D - Global Population",
    "titleCN": "Bar3D - 全球人口分布",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "bar3d-myth",
    "title": "Bar3D - Myth",
    "titleCN": "Bar3D - 星云",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "bar3d-noise-modified-from-marpi-demo",
    "title": "Noise modified from marpi's demo",
    "titleCN": "基于 marpi 示例修改的噪声效果",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "bar3d-punch-card",
    "title": "Bar3D - Punch Card",
    "titleCN": "Bar3D - 打卡统计柱状图",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "bar3d-simplex-noise",
    "title": "Bar3D - Simplex Noise",
    "titleCN": "Bar3D - 单纯形噪声",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "bar3d-voxelize-image",
    "title": "Voxelize image",
    "titleCN": "图像体素化",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "flowGL-noise",
    "title": "Flow on the cartesian",
    "titleCN": "直角坐标系上的向量场",
    "category": [
      "flowGL"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "global-population-bar3d-on-globe",
    "title": "Global Population - Bar3D on Globe",
    "titleCN": "全球人口分布 - 地球上的 Bar3D",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "globe-contour-paint",
    "title": "Contour Paint",
    "titleCN": "等值线渲染",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "globe-displacement",
    "title": "Globe Displacement",
    "titleCN": "地形位移",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "globe-moon",
    "title": "Moon",
    "titleCN": "月球",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "graphgl-gpu-layout",
    "title": "GraphGL - GPU Layout",
    "titleCN": "GraphGL - GPU 布局",
    "category": [
      "graphGL"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "graphgl-large-internet",
    "title": "GraphGL - Large Internet",
    "titleCN": "GraphGL - 大规模互联网图谱",
    "category": [
      "graphGL"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "graphgl-npm-dep",
    "title": "NPM Dependencies with graphGL",
    "titleCN": "1w 节点 2w7 边的 NPM 依赖图",
    "category": [
      "graphGL"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "image-surface-sushuang",
    "title": "Image Surface Sushuang",
    "titleCN": "Image Surface Sushuang",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "image-to-bar3d",
    "title": "Image to Bar3D",
    "titleCN": "图像转三维柱状图",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "iron-globe",
    "title": "Iron globe",
    "titleCN": "铁质感地球",
    "category": [
      "globe"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "line3d-orthographic",
    "title": "Line3D - Orthographic Projection",
    "titleCN": "三维折线图 - 正交投影",
    "category": [
      "line3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "lines3d-airline-on-globe",
    "title": "Airline on Globe",
    "titleCN": "Airline on Globe",
    "category": [
      "lines3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "lines3d-flights",
    "title": "Flights",
    "titleCN": "Flights",
    "category": [
      "lines3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "lines3d-flights-gl",
    "title": "Flights GL",
    "titleCN": "Flights GL",
    "category": [
      "lines3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "lines3d-flights-on-geo3d",
    "title": "Flights on Geo3D",
    "titleCN": "Flights on Geo3D",
    "category": [
      "lines3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "linesGL-ny",
    "title": "Use linesGL to draw 1 million New York streets",
    "titleCN": "LinesGL - 实时交互的纽约街道可视化",
    "category": [
      "linesGL"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "map3d-buildings",
    "title": "Buildings",
    "titleCN": "三维建筑",
    "category": [
      "map3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "map3d-wood-city",
    "title": "Wood City",
    "titleCN": "木质风格城市",
    "category": [
      "map3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "metal-bar3d",
    "title": "Metal Bar3D",
    "titleCN": "三维柱状图 - 金属质感",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "metal-surface",
    "title": "Metal Surface",
    "titleCN": "Metal Surface",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "parametric-surface-rose",
    "title": "Parametric Surface Rose",
    "titleCN": "Parametric Surface Rose",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "scatter3d",
    "title": "Scatter3D",
    "titleCN": "三维散点图",
    "category": [
      "scatter3D"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "scatter3D-dataset",
    "title": "3D Scatter with Dataset",
    "titleCN": "使用 dataset 为三维散点图设置数据",
    "category": [
      "scatter3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "scatter3d-globe-population",
    "title": "Scatter3D - Global Population",
    "titleCN": "三维散点图 - 全球人口分布",
    "category": [
      "scatter3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "scatter3d-orthographic",
    "title": "Scatter3D - Orthographic",
    "titleCN": "三维散点图 - 正交投影",
    "category": [
      "scatter3D"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "scatter3d-scatter",
    "title": "3D Scatter with Scatter Matrix",
    "titleCN": "三维散点图和散点矩阵结合使用",
    "category": [
      "scatter3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "scatter3d-simplex-noise",
    "title": "Scatter3D - Simplex Noise",
    "titleCN": "三维散点图 - 单纯形噪声",
    "category": [
      "scatter3D"
    ],
    "isGL": true,
    "ts": false,
    "theme": "dark"
  },
  {
    "id": "scatterGL-gps",
    "title": "10 million Bulk GPS points",
    "titleCN": "1 千万 GPS 点可视化",
    "category": [
      "scatterGL"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "simple-surface",
    "title": "Simple Surface",
    "titleCN": "Simple Surface",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "sphere-parametric-surface",
    "title": "Sphere Parametric Surface",
    "titleCN": "Sphere Parametric Surface",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "stacked-bar3d",
    "title": "Stacked Bar3D",
    "titleCN": "三维堆叠柱状图",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "surface-breather",
    "title": "Breather",
    "titleCN": "Breather",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "surface-golden-rose",
    "title": "Golden Rose",
    "titleCN": "Golden Rose",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "surface-leather",
    "title": "Leather Material",
    "titleCN": "皮革材质",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "surface-mollusc-shell",
    "title": "Mollusc Shell",
    "titleCN": "Mollusc Shell",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "surface-theme-roses",
    "title": "Theme Roses",
    "titleCN": "Theme Roses",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "surface-wave",
    "title": "Surface Wave",
    "titleCN": "Surface Wave",
    "category": [
      "surface"
    ],
    "isGL": true,
    "ts": false
  },
  {
    "id": "transparent-bar3d",
    "title": "Transparent Bar3D",
    "titleCN": "三维柱状图 - 透明效果",
    "category": [
      "bar3D"
    ],
    "isGL": true,
    "ts": false
  }
];

/** Match the category-priority ordering of the original Explore.vue. */
export function getExamplesForCategory(category: string): EChartsOfficialExample[] {
  return ECHARTS_EXAMPLES.filter((example) => example.category.includes(category)).sort(
    (a, b) => Number(a.isGL) - Number(b.isGL) || a.category.indexOf(category) - b.category.indexOf(category),
  );
}

/** Fixed example themes take precedence, just as in upstream ExampleCard.vue. */
export function getExampleThumbnail(example: EChartsOfficialExample, darkMode = false): string {
  const theme = example.theme || (darkMode ? "dark" : "");
  return `/echarts-official/${example.isGL ? "data-gl" : "data"}/thumb${theme ? `-${theme}` : ""}/${example.id}.webp`;
}
